name: Auth Service CI -I OM

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source Code -1
        uses: actions/checkout@v4

      - name: Setup Java 21 -2
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build Project -3
        run: mvn clean package

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: auth-service-jar
          path: target/*.jar
